[package]
name = "inventory_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
futures-util = "0.3.31"
mongodb = "3.2.1"
once_cell = "1.20.3"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
